### ISSUE TITLE
Random timeout while downloading big game

### ISSUE THREAD

**Issue by MInecrafterPictures** [Xpl0itU/WiiUDownloader#88] opened 2024-04-04 09:41 UTC
I tried downloading a 7+ GB game and it gave me a timeout error for no reason.
The downloading freezes mid-way through.
![image](https://github.com/Xpl0itU/WiiUDownloader/assets/67380524/1e3228de-3fe7-4799-83b8-81416539c957)

**Comment by MInecrafterPictures** [comment] 2024-04-04 09:42
I managed to download its much smaller DLC though

**Comment by AHuski** [comment] 2024-04-07 23:36
I had an issue where it would only download the first 37 MB. Switching to version 2.29 fixed it, so you could try that.  [https://github.com/Xpl0itU/WiiUDownloader/releases/tag/v2.29](url)

**Comment by jpaoad31** [comment] 2024-04-09 03:57
I just tried the newest version as well, ran into the same issue on MacOS for WATCH_DOGS, so the issue is not platform specific. Went back to the previous version I had (also happens to be 2.29) and didn't have any issues.

**Comment by sibwaze** [comment] 2024-04-09 20:29
confirm that the current version causes the problem, specifically when trying to install dlc for TLOZ: Breath Of The Wild
Went back to 2.29 and everything seems to work fine!

**Comment by Xpl0itU** [comment] 2024-04-10 14:46
I would like to try to close this issue, could you all try with this version? https://github.com/Xpl0itU/WiiUDownloader/releases/tag/v2.42

**Comment by AHuski** [comment] 2024-04-10 17:16
> I would like to try to close this issue, could you all try with this version? https://github.com/Xpl0itU/WiiUDownloader/releases/tag/v2.42

![Screenshot_20240410_111234](https://github.com/Xpl0itU/WiiUDownloader/assets/88903325/79ea6325-cd70-4903-b55b-d06c16356ce3)

I got this error when downloading the DLC for Breath of the Wild. I believe the game and update downloaded successfully, though.

**Comment by allengray69** [comment] 2024-04-11 01:56
2.42 = keep getting context deadline exceeded

**Comment by Xpl0itU** [comment] 2024-04-14 16:02
Fixed with v2.50 and later https://github.com/Xpl0itU/WiiUDownloader/releases/latest

**Closed by Xpl0itU** 2024-04-14 16:02 UTC
